# Generated by Django 4.1.7 on 2023-06-24 15:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foret',
            fields=[
                ('id_foret', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('superficie', models.FloatField()),
                ('localisation', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('densite', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Incendie',
            fields=[
                ('id_incendie', models.AutoField(primary_key=True, serialize=False)),
                ('annee_incendie', models.IntegerField()),
                ('numero', models.CharField(max_length=100)),
                ('date_eclosion', models.DateField(default=django.utils.timezone.now)),
                ('foret_domaniale', models.CharField(max_length=100)),
                ('commune_rurale', models.CharField(max_length=100)),
                ('ccdrf', models.CharField(max_length=100)),
                ('superficie_incendiee', models.FloatField()),
                ('id_foret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incendie_foret.foret')),
            ],
        ),
    ]
